name: "Create ArgoCD Applications"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "environments/test/configuration/values.yaml"
      - "environments/prod/configuration/values.yaml"
      - "terraform/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  apply-changes:
    name: "Apply Changes"
    uses: unir-tfm-devops/reusable-github-actions/.github/workflows/terraform-apply-azure.yml@main
    secrets: inherit
